---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: accountpools.aws.managed.openshift.io
spec:
  group: aws.managed.openshift.io
  names:
    kind: AccountPool
    listKind: AccountPoolList
    plural: accountpools
    singular: accountpool
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Desired pool size
      jsonPath: .status.poolSize
      name: Pool Size
      type: integer
    - description: Number of unclaimed accounts
      jsonPath: .status.unclaimedAccounts
      name: Unclaimed Accounts
      type: integer
    - description: Number of claimed accounts
      jsonPath: .status.claimedAccounts
      name: Claimed Accounts
      type: integer
    - description: Number of ready accounts
      jsonPath: .status.availableAccounts
      name: Available Accounts
      type: integer
    - description: Number of accounts progressing towards ready
      jsonPath: .status.accountsProgressing
      name: Accounts Progressing
      type: integer
    - description: Difference between accounts created and soft limit
      jsonPath: .status.awsLimitDelta
      name: AWS Limit Delta
      type: integer
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AccountPool is the Schema for the accountpools API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AccountPoolSpec defines the desired state of AccountPool
            properties:
              poolSize:
                type: integer
            required:
            - poolSize
            type: object
          status:
            description: AccountPoolStatus defines the observed state of AccountPool
            properties:
              accountsProgressing:
                description: AccountsProgressing shows the approximate value of the
                  number of accounts that are in the creation workflow (Creating,
                  PendingVerification, InitializingRegions)
                type: integer
              availableAccounts:
                description: AvailableAccounts denotes accounts that HAVE NEVER BEEN
                  CLAIMED, so NOT reused, and are READY to be claimed.  This differs
                  from the UnclaimedAccounts, who similarly HAVE NEVER BEEN CLAIMED,
                  but include ALL non-FAILED states
                type: integer
              awsLimitDelta:
                description: AWSLimitDelta shows the approximate difference between
                  the number of AWS accounts currently created and the limit. This
                  should be the same across all hive shards in an environment
                type: integer
              claimedAccounts:
                description: ClaimedAccounts is an approximate value representing
                  the amount of accounts that are currently claimed
                type: integer
              poolSize:
                type: integer
              unclaimedAccounts:
                description: UnclaimedAccounts is an approximate value representing
                  the amount of non-failed accounts
                type: integer
            required:
            - accountsProgressing
            - availableAccounts
            - awsLimitDelta
            - claimedAccounts
            - poolSize
            - unclaimedAccounts
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
