apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: accountpools.aws.managed.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.poolsize
    name: Pool Size
    type: integer
  - JSONPath: .status.unclaimedaccounts
    name: Unclaimed Accounts
    type: integer
  - JSONPath: .status.claimedaccounts
    name: Claimed Accounts
    type: integer
  group: aws.managed.openshift.io
  names:
    kind: AccountPool
    listKind: AccountPoolList
    plural: accountpools
    singular: accountpool
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            poolsize:
              format: int64
              type: integer
          required:
          - poolsize
          type: object
        status:
          properties:
            claimedaccounts:
              format: int64
              type: integer
            poolsize:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              format: int64
              type: integer
            unclaimedaccounts:
              format: int64
              type: integer
          required:
          - poolsize
          - unclaimedaccounts
          - claimedaccounts
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
