apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-account-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-account-operator
  template:
    metadata:
      labels:
        name: aws-account-operator
    spec:
      serviceAccountName: aws-account-operator
      containers:
        - name: aws-account-operator
          # Replace this with the built image name
          # This will get replaced on deploy by /hack/generate-operator-bundle.py
          image: quay.io/app-sre/aws-account-operator:latest
          command:
          - aws-account-operator
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aws-account-operator"
